### ISSUE TITLE
holo/service/confirm: Cannot read property 'agent_id' of undefined

### ISSUE THREAD

**Issue by zo-el** [Holo-Host/holo-envoy#23]
when we make a `holo/service/confirm` from chaperone it returns 
```=json
{code: -32000, message: "TypeError", data: "Cannot read property 'agent_id' of undefined"}
```
These are the logs from envoy when we see this error:
![Screenshot from 2020-09-21 16-28-24](https://user-images.githubusercontent.com/29548571/93825974-e42a6b80-fc2b-11ea-884b-eac0988ce06b.png)

**Comment by mjbrisebois** [comment]
Upon first glance, I think the issue is because the mock is returning the same response all the time.  Envoy needs a unique commit hash in order to resolve each pending confirmation separately.  Without a unique hash, there will be multiple confirmations triggered for the same pending ID.  The first one will complete and [remove](https://github.com/Holo-Host/holo-envoy/blob/develop/src/index.ts#L539) while the rest will trigger this error.

Get pending will be undefined after the first confirmation was successful.

https://github.com/Holo-Host/holo-envoy/blob/develop/src/index.ts#L701-L703
```javascript
    getPendingConfirmation ( res_log_hash ) {
	return this.pending_confirms[ res_log_hash ];
    }
```

cc @zo-el

**Comment by zo-el** [comment]
@mjbrisebois 
Understood. Ill make the necessary changes the the dummy DNA. 
Thanks

**Comment by zo-el** [comment]
@mjbrisebois - Good call. I updated the dummy DNA to returned the hash of the payload back to keep the response unique.
